export const questions1 = [
    "I try to be nice to other people. I care about their feelings",
    "I usually  share with others, for example food or drink",
    "I find it hard to think properly or concentarte",
    "I sometimes feel so tired, I just sit around and do nothing",
    "I have at least one good friend",
    "I think i would never be as good as other kids",
    "I feel afraid of being alone on my own at home",
    "I think my family would be better off without me",
    "Most of my friends in school well in examinations",
    "I expect people to pay attention to whatever I post",
    "I would rather be alone than with other people",
    "My posts reflect on my current mood",
    "I think sad or scary thoughts over and over again",
    "I do things I am not supposed to do",
    "I feel lonely",
    "I am honest with my parents when they ask about my academic preformance",
    "I get a lot of headaches, stomach-aches or sickness",
    "My friends are pressurise me to do things I don't want to",
    "Going through my social media pages makes me feel disappointed in myself",
    "I feel bad about myself, or don't like myself",
    "I feel upset when my parents value what others think about me",
    "I spend most of my time in school with friends discussing academic work/revising for examination",
    "I worry when I think I have done poorly at something",
    "I get along better with older people than with people of my own age",
    "Other people pick on me or bully me"
  ];

  export const questions2 = [
    "I try to be nice to other people, I care about their feelings",
    "I am restless, I find it hard to sit down for long",
    "I get a lot of headaches, stomach-aches or sickness",
    "I usually share with others, for example food or drink",
    "I get very angry and often lose my temper",
    "I would rather be alone than with other people",
    "I am generally willing to do what other people want",
    "I worry a lot",
    "I am helpful if someone is hurt, upset or feeling ill",
    "I am constantly fidgeting or squirming",
    "I have at least one good friend",
    "I fight a lot. I can make other peopledo what I want",
    "I am often unhappy, depressed or tearful",
    "Other people generally like me",
    "I am easily distracted, I find it difficult to concentrate",
    "I am nervous in new situations, I easily lose confidense",
    "I am kind to children",
    "I am often accussed of lying or cheating",
    "Other people pick on me or bully me",
    "I often offer to help others(family members, friends, colleagues)",
    "I think before I do things",
    "I take thinkgs that are not mine from home, work or elsewhere",
    "I get along better with older people than with people of my own age",
    "I have many fears, I am easily scared",
    "I finish the work I'm doing. My attention is good"
]

export const questions3 = [
    "Most of my friends in school perform well in examinations",
    "My friends encourage me to work hard in the school.",
    "My friends affect my academic work positively.",
    "My friends make fun of students who try to do well in school.",
    "I spend most of my time in school with friends discussing academic work/revising for examination.",
    "My friends are pressurise me to do things I don't want to.",
    "Most of my friends are disciplined in school and at home.",
    "I feel compelled to do things my friends tell me to do.",
    "Making my parents proud is a priority in my life.",
    "It is my duty as a son or daughter to meet my parents's expections.",
    "Making my parents happy is more important than making myself happy.",
    "It is my responsibility to care of my parents.",
    "I have argued with my parents about academics in the past.",
    "I am honest with my parents when they ask about my academic performance.",
    "I find it difficult to live up to my parent's academic expections.",
    "I worry about disappointing my parents.",
    "I feel upset when my parents value what others think about me."   
]