
export const questions = [
    "I try to be nice to other people. I care about their feelings",
    "I usually  share with others, for example food or drink",
    "I find it hard to think properly or concentarte",
    "I sometimes feel so tired, I just sit around and do nothing",
    "I have at least one good friend",
    "I think i would never be as good as other kids",
    "I feel afraid of being alone on my own at home",
    "I think my family would be better off without me",
    "Most of my friends in school well in examinations",
    "I expect people to pay attention to whatever I post",
    "I would rather be alone than with other people",
    "My posts reflect on my current mood",
    "I think sad or scary thoughts over and over again",
    "I do things I am not supposed to do",
    "I feel lonely",
    "I am honest with my parents when they ask about my academic preformance",
    "I get a lot of headaches, stomach-aches or sickness",
    "My friends are pressurise me to do things I don't want to",
    "Going through my social media pages makes me feel disappointed in myself",
    "I feel bad about myself, or don't like mtself",
    "I feel upset when my parents value what others think about me",
    "I spend most of my time in school with friends discussing academic work/revising for examination",
    "I worry when I think I have done poorly at something",
    "I get along better with older people than with people of my own age",
    "Other people pick on me or bully me"
  ];