export const questions = [
    "I try to be nice to other people, I care about their feelings",
    "I am restless, I find it hard to sit down for long",
    "I get a lot of headaches, stomach-aches or sickness",
    "I usually share with others, for example food or drink",
    "I get very angry and often lose my temper",
    "I would rather be alone than with other people",
    "I am generally willing to do what other people want",
    "I worry a lot",
    "I am helpful if someone is hurt, upset or feeling ill",
    "I am constantly fidgeting or squirming",
    "I have at least one good friend",
    "I fight a lot. I can make other peopledo what I want",
    "I am often unhappy, depressed or tearful",
    "Other people generally like me",
    "I am easily distracted, I find it difficult to concentrate",
    "I am nervous in new situations, I easily lose confidense",
    "I am kind to children",
    "I am often accussed of lying or cheating",
    "Other people pick on me or bully me",
    "I often offer to help others(family members, friends, colleagues)",
    "I think before I do things",
    "I take thinkgs that are not mine from home, work or elsewhere",
    "I get along better with older people than with people of my own age",
    "I have many fears, I am easily scared",
    "I finish the work I'm doing. My attention is good"
]